### PR TITLE
working vega component that support altair charts and vega dict

### PR DESCRIPTION
**Pull request by LeoGrosjean**
This is still work in progress

You can check @Alek99 my issues with how events should work

I will remove all comments and TODOs

I have an issue with serializer, I will open a ticket / PR to allow serializer overwrite

### CODE REVIEW

**Review by Alek99 — CHANGES_REQUESTED** [review]
Thanks for making the PR! Can you separate the Vega and Altair into different folders and make them separate PRs. We will publish them separately as different packages

**Comment by LeoGrosjean** [comment]
Hey @Alek99 !

I'm still ~~working~~ struggling  on :
- signal_listeners
- on_new_view

> Props `on_new_view`
> ```js
> onNewView={(view) => {
>    view.addEventListener("click", (_e, item) => console.log(item)); # state event instaid !
>    view.addEventListener("hover", (_e, item) => console.log(item)); # state event instaid !
>  }}
> ```

As asked, I renamed custom component as altair only to keep only python and avoid custom js !

**Comment by LeoGrosjean** [comment]
I added support for `onNewView` 

It get construct from those props :
```python
on_new_view_click
on_new_view_dblclick
...
on_new_view_dragleave
```

Sadely page reload and all selection are removed when event is trigger (big charts can also flash)

**Comment by LeoGrosjean** [comment]
All flashing and page reload has been fixed !
Altair is ready to be used at his max potential in reflex !

**Comment by Euraxluo** [comment]
please pass the merge

@LeoGrosjean @Alek99 @adhami3310

**Comment by Euraxluo** [comment]
@carlosabadia

plz let this pr pass.
Don't let the work go to waste

@LeoGrosjean @carlosabadia

**Review by picklelo — APPROVED** [review]
Tried the demo and it works great - nice work!

**Pull request merged**
